language: node_js
node_js:
  - "8"
  - "10"
cache: yarn

install:
  - yarn global add lerna
  - lerna bootstrap

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  provider: script
  script: lerna publish from-package --yes --no-git-tag-version --no-push
  skip_cleanup: true
  on:
    node: "10"
    branch: release
